/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author jhoni
 */
public class AggPlanta extends javax.swing.JFrame {

    Principal principal = new Principal();
    
    public AggPlanta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelCantPlantas = new javax.swing.JLabel();
        jLabelHumedadMin = new javax.swing.JLabel();
        jLabelViewAgg = new javax.swing.JLabel();
        jlabelNombre = new javax.swing.JLabel();
        jTextFieldNivelMin = new javax.swing.JTextField();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabelHumedadMax = new javax.swing.JLabel();
        jTextFieldNivelMax = new javax.swing.JTextField();
        bttn_agg_planta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 130, -1));

        jLabelCantPlantas.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCantPlantas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCantPlantas.setText("Cantidad de plantas");
        jPanel2.add(jLabelCantPlantas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabelHumedadMin.setBackground(new java.awt.Color(0, 0, 0));
        jLabelHumedadMin.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHumedadMin.setText("Nivel de humedad mínimo: ");
        jPanel2.add(jLabelHumedadMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 170, 20));

        jLabelViewAgg.setBackground(new java.awt.Color(0, 0, 0));
        jLabelViewAgg.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabelViewAgg.setForeground(new java.awt.Color(0, 0, 0));
        jLabelViewAgg.setText("Agregar plantas");
        jPanel2.add(jLabelViewAgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jlabelNombre.setBackground(new java.awt.Color(0, 0, 0));
        jlabelNombre.setForeground(new java.awt.Color(0, 0, 0));
        jlabelNombre.setText("Nombre: ");
        jPanel2.add(jlabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jTextFieldNivelMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNivelMinActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldNivelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 130, -1));

        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 130, -1));

        jLabelHumedadMax.setBackground(new java.awt.Color(0, 0, 0));
        jLabelHumedadMax.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHumedadMax.setText("Nivel de humedad máximo: ");
        jPanel2.add(jLabelHumedadMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 170, 20));

        jTextFieldNivelMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNivelMaxActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldNivelMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 130, -1));

        bttn_agg_planta.setText("Agregar");
        bttn_agg_planta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_agg_plantaActionPerformed(evt);
            }
        });
        jPanel2.add(bttn_agg_planta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 200, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldNivelMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNivelMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNivelMinActionPerformed

    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

    private void jTextFieldNivelMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNivelMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNivelMaxActionPerformed

    private void bttn_agg_plantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_agg_plantaActionPerformed
        principal.t_table[0]=jTextFieldNombre.getText();
        principal.t_table[1]=jTextFieldCantidad.getText();
        principal.t_table[2]=jTextFieldNivelMax.getText();
        principal.t_table[2]=jTextFieldNivelMin.getText();
        
        this.setVisible(false);
    }//GEN-LAST:event_bttn_agg_plantaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AggPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AggPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AggPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AggPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AggPlanta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_agg_planta;
    private javax.swing.JLabel jLabelCantPlantas;
    private javax.swing.JLabel jLabelHumedadMax;
    private javax.swing.JLabel jLabelHumedadMin;
    private javax.swing.JLabel jLabelViewAgg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldNivelMax;
    private javax.swing.JTextField jTextFieldNivelMin;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JLabel jlabelNombre;
    // End of variables declaration//GEN-END:variables
}
