/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Vistas;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhoni
 */
public class Principal extends javax.swing.JFrame {
    
    //Variables globales
    DefaultTableModel tabla_modelo;

    /** Creates new form Principal */
    public Principal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_inventario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        SimulacionButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(905, 603));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("SISTEMA DE RIEGO AUTOMATIZADO");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 430, 30));

        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        table_inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Romero", "4", "20", "40"},
                {"Tomillo", "3", "20", "40"},
                {"Menta", "3", "50", "60"},
                {"Albahaca", "5", "50", "60"},
                {"Oregano", "7", "30", "40"}
            },
            new String [] {
                "Nombre", "Cantidad", "Valor Minimo de Humedad", "valor Maximo de Humedad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_inventario.setToolTipText("");
        table_inventario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(table_inventario);
        inicializarTabla();

        jLayeredPane1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, 110));

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SimulacionButton1.setBackground(new java.awt.Color(102, 255, 102));
        SimulacionButton1.setText("Empezar simulación");
        SimulacionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimulacionButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(SimulacionButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 160, 70));

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 240, 260));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarTabla() {
        tabla_modelo = new DefaultTableModel();
        
        tabla_modelo.addColumn("Nombre");
        tabla_modelo.addColumn("Cantidad");
        tabla_modelo.addColumn("Valor mínimo de humedad");
        tabla_modelo.addColumn("Valor Máximo de humedad");
    }
    
    private void SimulacionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimulacionButton1ActionPerformed
        Simulacion formulario = new Simulacion();
        formulario.setVisible(true);
    }//GEN-LAST:event_SimulacionButton1ActionPerformed

    public void agregarFila(String[] fila) {
    try {
        if (tabla_modelo == null) {
            System.out.println("Modelo de tabla nulo en agregarFila");
            inicializarTabla();
        }

        tabla_modelo.addRow(fila);

        // Imprimir el contenido del modelo
        for (int i = 0; i < tabla_modelo.getRowCount(); i++) {
            System.out.println("Fila " + i + ": " + tabla_modelo.getDataVector().elementAt(i));
        }
        } catch (Exception e) {
            System.out.println("Error al agregar fila: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SimulacionButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_inventario;
    // End of variables declaration//GEN-END:variables

}
