/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import com.mycompany.riego_automatizado.modulo;
import com.mycompany.riego_automatizado.*;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
/**
 *
 * @author admin
 */
public class Simulacion extends javax.swing.JFrame {

    /**
     * Creates new form Simulacion
     */
    
    public Simulacion() {
        initComponents();

        cantromero.setText(String.valueOf(plantas[0].getCant_plantas()));
        canttomillo.setText(String.valueOf(plantas[1].getCant_plantas()));
        cantmenta.setText(String.valueOf(plantas[3].getCant_plantas()));
        cantalbahaca.setText(String.valueOf(plantas[2].getCant_plantas()));
        cantoregano.setText(String.valueOf(plantas[4].getCant_plantas()));
        
        // Crear un temporizador que se ejecute cada 10 segundos
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Actualizar la información cada 10 segundos
                actualizarInformacion();
            }
        });

        // Iniciar el temporizador
        timer.start();

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(300, 200);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelHora = new javax.swing.JLabel();
        LabelDiaNoche = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        romeroh = new javax.swing.JLabel();
        labelTemperatura = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LabelTanque = new javax.swing.JLabel();
        Labellluvia = new javax.swing.JLabel();
        riegoh = new javax.swing.JLabel();
        mentar = new javax.swing.JLabel();
        mentah = new javax.swing.JLabel();
        oreganor = new javax.swing.JLabel();
        oreganoh = new javax.swing.JLabel();
        riegot = new javax.swing.JLabel();
        tomilloh = new javax.swing.JLabel();
        albahacar = new javax.swing.JLabel();
        albahacah = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        hromero = new javax.swing.JLabel();
        rromero = new javax.swing.JLabel();
        hmenta = new javax.swing.JLabel();
        rmenta = new javax.swing.JLabel();
        horegano = new javax.swing.JLabel();
        roregano = new javax.swing.JLabel();
        htomillo = new javax.swing.JLabel();
        rtomillo = new javax.swing.JLabel();
        halbahaca = new javax.swing.JLabel();
        ralbahaca = new javax.swing.JLabel();
        cantromero = new javax.swing.JLabel();
        cantmenta = new javax.swing.JLabel();
        cantoregano = new javax.swing.JLabel();
        canttomillo = new javax.swing.JLabel();
        cantalbahaca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulacion!");
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(905, 800));
        setSize(new java.awt.Dimension(1000, 1000));

        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Hora:");

        LabelHora.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LabelHora.setText("0");

        LabelDiaNoche.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LabelDiaNoche.setText("Noche");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/romero.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tomillo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setVerifyInputWhenFocusTarget(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menta.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/albahaca.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/oregano.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        romeroh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        romeroh.setText("Humedad:");

        labelTemperatura.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTemperatura.setText("0");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setText("Nivel de tanque:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("Temperatura:");

        LabelTanque.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LabelTanque.setText("80");

        Labellluvia.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Labellluvia.setText("LLuvia!");
        Labellluvia.setEnabled(false);

        riegoh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        riegoh.setText("Riego:");

        mentar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mentar.setText("Riego:");

        mentah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mentah.setText("Humedad:");

        oreganor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        oreganor.setText("Riego:");

        oreganoh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        oreganoh.setText("Humedad:");

        riegot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        riegot.setText("Riego:");

        tomilloh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tomilloh.setText("Humedad:");

        albahacar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        albahacar.setText("Riego:");

        albahacah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        albahacah.setText("Humedad:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Oregano");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Albahaca");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Menta");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Romero");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setText("Tomillo");

        hromero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hromero.setText("0");

        rromero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rromero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luzroja.png"))); // NOI18N
        rromero.setMaximumSize(new java.awt.Dimension(40, 40));
        rromero.setMinimumSize(new java.awt.Dimension(40, 40));
        rromero.setPreferredSize(new java.awt.Dimension(40, 40));

        hmenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hmenta.setText("0");

        rmenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rmenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luzroja.png"))); // NOI18N

        horegano.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        horegano.setText("0");

        roregano.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roregano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luzroja.png"))); // NOI18N

        htomillo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        htomillo.setText("0");

        rtomillo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtomillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luzroja.png"))); // NOI18N

        halbahaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        halbahaca.setText("0");

        ralbahaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ralbahaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luzroja.png"))); // NOI18N

        cantromero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantromero.setText("0");

        cantmenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantmenta.setText("0");

        cantoregano.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantoregano.setText("0");

        canttomillo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        canttomillo.setText("0");

        cantalbahaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantalbahaca.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel16)
                                    .addGap(157, 157, 157)
                                    .addComponent(jLabel15)
                                    .addGap(131, 131, 131)
                                    .addComponent(jLabel13))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LabelHora))
                                .addComponent(LabelDiaNoche)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(riegot)
                                        .addComponent(tomilloh))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rtomillo)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(33, 33, 33)
                                            .addComponent(htomillo))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel17)
                                    .addGap(152, 152, 152)
                                    .addComponent(jLabel14))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rromero, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(canttomillo)
                                    .addGap(64, 64, 64)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(albahacar)
                                                .addComponent(albahacah))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ralbahaca)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(33, 33, 33)
                                                    .addComponent(halbahaca))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cantalbahaca)))))
                            .addContainerGap(473, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(riegoh)
                                        .addComponent(romeroh))
                                    .addGap(45, 45, 45)
                                    .addComponent(hromero))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cantromero)))
                            .addGap(50, 50, 50)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mentar)
                                        .addComponent(mentah))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(hmenta))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rmenta))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cantmenta)))
                            .addGap(47, 47, 47)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(oreganoh)
                                        .addComponent(oreganor))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(roregano)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(33, 33, 33)
                                            .addComponent(horegano))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cantoregano)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelTemperatura))
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Labellluvia))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LabelTanque)))
                            .addContainerGap()))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LabelDiaNoche)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(LabelHora))
                            .addGap(23, 23, 23)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(cantromero)
                                .addComponent(cantmenta)
                                .addComponent(cantoregano))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(Labellluvia)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelTemperatura)
                                .addComponent(jLabel10))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(LabelTanque))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(horegano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roregano))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(oreganoh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oreganor)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(romeroh)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(riegoh))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(hmenta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rmenta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(hromero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rromero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(mentah)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mentar)))
                            .addGap(32, 32, 32)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(canttomillo)
                                .addComponent(cantalbahaca))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(tomilloh)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(riegot))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(albahacah)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(albahacar))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(htomillo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rtomillo))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(halbahaca)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ralbahaca)))))
                    .addContainerGap()))
        );

        LabelHora.getAccessibleContext().setAccessibleName("LabelHora");
        LabelDiaNoche.getAccessibleContext().setAccessibleName("LabelDiaNoche");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /*
    Variables de la simulación
    */
    
    int hora = 0;
    boolean noche=true;
    double nivel_tanque = 80;
    double temperatura;
    int dias_pasados=0;
    boolean lluvia=false;
    
    modulo[] plantas = {new modulo("Romero",4,20,40),
                        new modulo("Tomillo",3,20,40),
                        new modulo("Albahaca",5,40,60),
                        new modulo("Menta",3,20,40),
                        new modulo("Oregano",7,20,40)};
    
    private void actualizarInformacion() {
        setAllFalse();
        //Hora
        cambiarHora();
        LabelHora.setText(String.valueOf(hora));
        
        //Temperatura
        calcularTemperatura();
        labelTemperatura.setText(String.valueOf(temperatura));
        
        //plantas
        for(int i=0; i<plantas.length;i++){
            plantas[i].reducir_humedad(temperatura);
            RevisarHumedad(plantas[i]);
        }
        actualizarLabels();
        RevisarRiego();
        
        //tanque
        LabelTanque.setText(String.valueOf(nivel_tanque));
        
        if(dias_pasados==2 && noche){
            lluvia=true;
            Labellluvia.setEnabled(true);
            nivel_tanque=80;
            dias_pasados=0;
        }
        else{
            lluvia = false;
            Labellluvia.setEnabled(false);
        }
    }
    
    private void RevisarHumedad(modulo p){
        if (p.getVlr_act_h()<p.getVlr_min_h()){
            p.setRiego(true);
            nivel_tanque -= p.regar();
        }
    }
    
    private void setAllFalse(){
        plantas[0].setRiego(false);
        plantas[1].setRiego(false);
        plantas[2].setRiego(false);
        plantas[3].setRiego(false);
        plantas[4].setRiego(false);
        
    }
    
    private void RevisarRiego(){
        //Revisar Romero
        if (plantas[0].getRiego()){
            rromero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luzverde.png")));
        }
        else if(!plantas[0].getRiego()){
            rromero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luzroja.png")));
        }
        
        //Revisar Tomillo
        if (plantas[1].getRiego()){
            rtomillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luzverde.png")));
        }
        else if(!plantas[1].getRiego()){
            rtomillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luzroja.png")));
        }
        
        //Revisar Menta
        if (plantas[3].getRiego()){
            rmenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luzverde.png")));
        }
        else if(!plantas[3].getRiego()){
            rmenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luzroja.png")));
        }
        
        //Revisar Albahaca
        if (plantas[2].getRiego()){
            ralbahaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luzverde.png")));
        }
        else if(!plantas[2].getRiego()){
            ralbahaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luzroja.png")));
        }
        
        //Revisar Oregano
        if (plantas[4].getRiego()){
            roregano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luzverde.png")));
        }
        else if(!plantas[4].getRiego()){
            roregano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luzroja.png")));
        }
    }
    
    private void cambiarHora(){
        //Suma+1 a la hora o se reinicia si llega a 23
        if (hora==23){
            hora = 0;
            dias_pasados+=1;
        }
        else{
            hora+=1;
        }
        
        //revisa si es de noche o de dia
        if (hora>=19 || hora<=6){
            noche = true;
            LabelDiaNoche.setText("Noche");
        }
        else{
            noche = false;
            LabelDiaNoche.setText("Día");
        }
    }

    
    private void calcularTemperatura(){
        if(noche){
            temperatura = (int) (Math.random()*(21-13+1)+13);
        }
        else{
            temperatura = (int) (Math.random()*(27-18+1)+18);
        }
    }
    
    private void actualizarLabels(){
        //Humedad
        hromero.setText(String.valueOf(plantas[0].getVlr_act_h()));
        htomillo.setText(String.valueOf(plantas[1].getVlr_act_h()));
        hmenta.setText(String.valueOf(plantas[3].getVlr_act_h()));
        halbahaca.setText(String.valueOf(plantas[2].getVlr_act_h()));
        horegano.setText(String.valueOf(plantas[4].getVlr_act_h()));
        
        //Riego
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDiaNoche;
    private javax.swing.JLabel LabelHora;
    private javax.swing.JLabel LabelTanque;
    private javax.swing.JLabel Labellluvia;
    private javax.swing.JLabel albahacah;
    private javax.swing.JLabel albahacar;
    private javax.swing.JLabel cantalbahaca;
    private javax.swing.JLabel cantmenta;
    private javax.swing.JLabel cantoregano;
    private javax.swing.JLabel cantromero;
    private javax.swing.JLabel canttomillo;
    private javax.swing.JLabel halbahaca;
    private javax.swing.JLabel hmenta;
    private javax.swing.JLabel horegano;
    private javax.swing.JLabel hromero;
    private javax.swing.JLabel htomillo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTemperatura;
    private javax.swing.JLabel mentah;
    private javax.swing.JLabel mentar;
    private javax.swing.JLabel oreganoh;
    private javax.swing.JLabel oreganor;
    private javax.swing.JLabel ralbahaca;
    private javax.swing.JLabel riegoh;
    private javax.swing.JLabel riegot;
    private javax.swing.JLabel rmenta;
    private javax.swing.JLabel romeroh;
    private javax.swing.JLabel roregano;
    private javax.swing.JLabel rromero;
    private javax.swing.JLabel rtomillo;
    private javax.swing.JLabel tomilloh;
    // End of variables declaration//GEN-END:variables
}
